# Generated by Django 4.1 on 2022-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('track', models.CharField(max_length=200)),
                ('smallTallk', models.CharField(max_length=200)),
            ],
        ),
    ]
