# Generated by Django 4.1 on 2022-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='university',
            field=models.CharField(choices=[('1', '서강대학교'), ('2', '연세대학교'), ('3', '이화여자대학교'), ('4', '홍익대학교')], max_length=5),
        ),
    ]
