# Generated by Django 4.1 on 2022-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0002_alter_person_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='track',
            field=models.CharField(choices=[('1', '백엔드'), ('2', '프론트엔드'), ('3', '기획/디자인')], max_length=10),
        ),
    ]
