# Generated by Django 4.1 on 2022-08-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0004_person_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='author',
        ),
    ]
