# Generated by Django 4.1 on 2022-08-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0013_person_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='author_id',
        ),
    ]
