# Generated by Django 4.1 on 2022-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0014_remove_person_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='author_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
