# Generated by Django 4.1 on 2022-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinchonapp', '0015_person_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
